-- MySQL Script generated by MySQL Workbench
-- Thu Apr 17 20:30:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_a1_2
-- -----------------------------------------------------

-- Criação do Banco de Dados (Schema)
-- -----------------------------------------------------
-- Schema mydb_a1_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_a1_2` DEFAULT CHARACTER SET utf8 ;
USE `mydb_a1_2` ;

-- Criação das Tabelas (Tables) com seus Atributos (Fields)
-- -----------------------------------------------------
-- Table `mydb_a1_2`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `cpf` CHAR(11) NULL,
  `endereco` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `data_nascimento` TIMESTAMP NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `tipo` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`universidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`universidades` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `cnpj` CHAR(14) NULL,
  `endereco` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`usuario_universidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`usuario_universidade` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `universidade_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuariosuniversidades_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_universidadesusuarios_idx` (`universidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuariosuniversidades`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_universidadesusuarios`
    FOREIGN KEY (`universidade_id`)
    REFERENCES `mydb_a1_2`.`universidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`tipos_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`tipos_postagens` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`postagens` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `conteudo` VARCHAR(255) NULL,
  `data_postagem` TIMESTAMP NULL,
  `tipo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuariopostagem_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tipopost_idx` (`tipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuariopostagem`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipopost`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `mydb_a1_2`.`tipos_postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`tipos_reacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`tipos_reacoes` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`reacoes_postadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`reacoes_postadas` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `data_postagem` TIMESTAMP NULL,
  `postagem_id` INT NULL,
  `reacao_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuariopostagem_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_postagemreacoes_idx` (`postagem_id` ASC) VISIBLE,
  INDEX `fk_reacoespostadas_idx` (`reacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarioreacoes`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagemreacoes`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `mydb_a1_2`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reacoespostadas`
    FOREIGN KEY (`reacao_id`)
    REFERENCES `mydb_a1_2`.`tipos_reacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`tipos_arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`tipos_arquivo` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`arquivos` (
  `id` INT NOT NULL,
  `diretorio` VARCHAR(255) NULL,
  `data_postagem` TIMESTAMP NULL,
  `tipo_arquivo_id` INT NULL,
  `postagem_id` INT NULL,
  `tamanho` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagensarquivos_idx` (`postagem_id` ASC) VISIBLE,
  INDEX `fk_tipoarquiv_idx` (`tipo_arquivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_postagensarquivos`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `mydb_a1_2`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoarquiv`
    FOREIGN KEY (`tipo_arquivo_id`)
    REFERENCES `mydb_a1_2`.`tipos_arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`comentarios` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `conteudo` VARCHAR(255) NULL,
  `data_postagem` TIMESTAMP NULL,
  `postagem_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuariopostagem_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_postagemcomentarios_idx` (`postagem_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuariocomentarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagemcomentarios`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `mydb_a1_2`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`seguidores` (
  `id` INT NOT NULL,
  `usuario_seguido` INT NULL,
  `usuario_seguidor` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usarioseguido_idx` (`usuario_seguido` ASC) VISIBLE,
  INDEX `fk_usuarioseguidor_idx` (`usuario_seguidor` ASC) VISIBLE,
  CONSTRAINT `fk_usarioseguido`
    FOREIGN KEY (`usuario_seguido`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarioseguidor`
    FOREIGN KEY (`usuario_seguidor`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`bloqueados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`bloqueados` (
  `id` INT NOT NULL,
  `usuario_bloqueado` INT NULL,
  `usuario_bloqueador` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usarioseguido_idx` (`usuario_bloqueado` ASC) VISIBLE,
  INDEX `fk_usuarioseguidor_idx` (`usuario_bloqueador` ASC) VISIBLE,
  CONSTRAINT `fk_usariosbloqueado`
    FOREIGN KEY (`usuario_bloqueado`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariosbloqueador`
    FOREIGN KEY (`usuario_bloqueador`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`grupos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`grupo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`grupo_usuario` (
  `id` INT NOT NULL,
  `usuario_id` INT NULL,
  `grupo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupouser_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_grupouser_grupos_idx` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `fk_grupouser`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupouser_grupos`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `mydb_a1_2`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_a1_2`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_a1_2`.`notificacoes` (
  `id` INT NOT NULL,
  `conteudo` VARCHAR(255) NULL,
  `postagem_id` INT NULL,
  `usuario_id` INT NULL,
  `visualizada` TINYINT(1) NULL,
  `data_notificacao` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notificaousuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_notificaopostagem_idx` (`postagem_id` ASC) VISIBLE,
  CONSTRAINT `fk_notificaousuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb_a1_2`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificaopostagem`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `mydb_a1_2`.`postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
